server:
  port: 8080
spring:
  application:
    name: guitar-project
  datasource:
    url: jdbc:mysql://localhost:3306/guitar-project
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# ?? MyBatis ??????????????????
mybatis:
  configuration:
    # ????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## ????? OSS ????
#aliyun:
#  oss:
#    endpoint: oss-cn-chengdu.aliyuncs.com
#    bucketName: food-fly
#
## ????
#jwt:
#  secret: "mysupersecretkey32byteslength!@#$%^&*"  # ?????????256?????????
#  expiration: 3600000  # ??????????????1???3600*1000?

#????
logging:
  # ?????TRACE < DEBUG < INFO < WARN < ERROR?
  level:
    root: INFO  # ??????
    com.example.service: DEBUG  # ????????????root?
    org.springframework.web: WARN  # Spring Web ??????

  # ??????????????
  file:
    name: logs/app.log  # ????????????????

  # ????????????
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"  # ?????
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"      # ????

  # ????????????????
  logback:
    rollingpolicy:
      max-file-size: 10MB  # ??????10MB
      max-history: 7       # ??7????
      total-size-cap: 100MB # ???????
